meio-pagamento:
  asaas:
    access-token: $aact_YTU5YTE0M2M2N2I4MTliNzk0YTI5N2U5MzdjNWZmNDQ6OjAwMDAwMDAwMDAwMDAwNTYyODQ6OiRhYWNoXzk4MmZkMDRkLTY3NDQtNGMxYi05NTMzLWVhMGZhODQwZWU2Mg==
    dominio: https://sandbox.asaas.com/